language: python

before_install:
 - export GALAXY_RELEASE=release_17.01
 - export PLANEMO_RELEASE=0.37.0

install:
 - pip install planemo==$PLANEMO_RELEASE
 - sudo apt-get install -y ant

script:
 - ant test
